<?php 
/**
 * CoolMS2 Money Module (http://www.coolms.com/)
 *
 * @link      http://github.com/coolms/money for the canonical source repository
 * @copyright Copyright (c) 2006-2015 Altgraphic, ALC (http://www.altgraphic.com)
 * @license   http://www.coolms.com/license/new-bsd New BSD License
 * @author    Dmitry Popov <d.popov@altgraphic.com>
 */

namespace CmsMoney;

// Set form fields classes and placeholders here
$this->fieldset->get('amount')->setOption('twbs', [
    'currency' => [
        'type' => 'element',
        'content' => 'currency',
        'placement' => 'append',
        'class' => 'selectpicker btn btn-default',
        'order' => 5950,
        'decorators' => [
            'inputGroupBtn',
        ],
    ],
]);

?>
<?= $this->formCollection($this->fieldset, true, false);
